project:
  type: website
  output-dir: docs

  

website:
  title: "쿼토 shinylive"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - template.qmd
      - helloworld.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
   - lightbox
lightbox: auto


