project:
  type: website
  output-dir: docs

lang: ko-KR
date-format: "YYYY 년 MM 월 DD일"

website:
  title: "쿼토 shinylive"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - template.qmd
      - helloworld.qmd
      - text: "경우의 수"
        menu: 
          - href: combinatorics.qmd
            text: "경우의 수"
          - href: combinatorics-dice.qmd
            text: "경우의 수: 주사위"            
          - href: combinatorics-coin.qmd
            text: "경우의 수: 동전"

format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true



filters:
  - lightbox
  - webr   
lightbox: auto

execute:
  freeze: auto

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console