---
title: "경우의 수"
subtitle: "경우의 수에 대해서 살펴본다."
format:
  html:
    resources: 
      - shinylive-sw.js
filters:
  - shinylive
editor_options: 
  chunk_output_type: console
---

# 경우의 수

우리는 매일 수많은 결정을 내린다. 아침에 일어나서 무엇을 입을지 결정하는 것부터 하루를 어떻게 보낼지, 어떤 음식을 먹을지, 이러한 모든 결정은 여러 선택지와 가능한 결과 사이에서 이루어진다. 예를 들어, 오늘 비가 올 확률이 50% 라면 우산을 가져갈지 말지 결정해야 한다. 이와 같이, 선택과 이에 따른 가능한 결과는 **경우의 수(Combinatorics)**[^cases]라는 수학적 개념으로 표현된다.

[^cases]: 경우의 수는 영어로 "Number of Cases" 또는 "Counting"으로 표현할수 있으며 수학의 한분야로 조합론(Combinatorics)으로 번역된다.

경우의 수는 가능한 모든 선택과 결과를 계산하고 이해하는 데 도움을 준다. 이는 미래의 불확실성을 다루고 더 나은 결정을 내리는 데 중요하다. 예를 들어, 사업을 시작할 때 가능한 모든 시나리오와 그에 따른 이익과 손실을 고려해야 한다. 이러한 계산을 통해 위험을 이해하고 준비하며 미래를 예측하는 데 도움을 준다.


# 기본 경우의 수

기본 경우의 수는 일반적으로 가능한 결과의 전체 수를 계산하는 것을 포함한다. 기본 경우의 수 문제는 종종 곱의 법칙과 합의 법칙을 사용하여 해결된다.

1. **단순 계산 예시**:
    - **주사위 던지기**: 주사위를 한 번 던지면 6개의 가능한 결과(1, 2, 3, 4, 5, 6)가 있다. 따라서, 모든 경우의 수는 6이다.

2. **곱의 법칙 예시**:
    - **동전 던지기**: 동전을 세 번 던진다고 가정하자. 각 동전 던지기는 2개의 가능한 결과(앞면 또는 뒷면)를 가진다. 따라서 총 경우의 수는 $2 \times 2 \times 2 = 8$이다.
    
3. **합의 법칙 예시**:
    - **주사위와 동전 던지기**: 주사위를 던지거나 동전을 던질 수 있다. 주사위를 던지면 6개의 가능한 결과가 있고, 동전을 던지면 2개의 가능한 결과가 있다. 따라서 총 경우의 수는 $6 + 2 = 8$이다.

## 수식으로 표현

기본 경우의 수를 수식으로 표현하는 것은 간단하다.

1. **단순 계산**: 가능한 결과의 수는 단순히 그 수를 나타낸다. 예를 들어, 주사위를 던질 때 경우의 수는 $6$이다.

2. **곱의 법칙**: 두 이상의 **독립**적인 사건이 있을 때, 첫 번째 사건의 가능한 결과의 수와 두 번째 사건의 가능한 결과의 수를 곱하여 총 경우의 수를 찾는다.
    - 수식: $N = n_1 \times n_2 \times \ldots \times n_k$
    - $N$은 총 경우의 수이고, $n_1, n_2, \ldots, n_k$는 각각의 사건에 대한 가능한 결과의 수이다.

3. **합의 법칙**: 두 이상의 **상호 배타적인** 사건이 있을 때, 각 사건의 가능한 결과의 수를 더하여 총 경우의 수를 찾는다.
    - 수식: $N = n_1 + n_2 + \ldots + n_k$
    - $N$은 총 경우의 수이고, $n_1, n_2, \ldots, n_k$는 각각의 사건에 대한 가능한 결과의 수이다.

## R 코드

주사위 한번 던지기, 동전 3번 던지기, 주사위와 동전 함께 던지는 경우의 수를 계산해보자.


### 주사위

```{webr-r}
# 주사위 던지기: 6면체 주사위
dice <- c(1, 2, 3, 4, 5, 6)
# 가능한 모든 결과 생성
(all_results <- expand.grid(dice))
# 경우의 수 출력
nrow(all_results)  # 출력: 6
```


### 동전 3번 던지기

```{webr-r}
# 코인 던지기: 앞면(Head)과 뒷면(Tail)
coin <- c("앞면", "뒷면")
# 3번 동전 던지기의 가능한 모든 결과 생성
(all_results <- expand.grid(coin, coin, coin))
# 경우의 수 출력
nrow(all_results)  # 출력: 8
```

### 동전과 주사위 던지기

```{webr-r}
# 가능한 모든 결과 생성 (동전 던지기 + 주사위 던지기)
(all_results <- expand.grid(dice, coin))
# 경우의 수 출력
nrow(all_results)  # 출력: 12
```


